const RoutesRegistry = {
  getTestAPI: {
    name: "",
    url: "",
    authRequired: true,
    title: "",
    description: "",
    keywords: "",
    extraInfo: "",
    source: "",
    _status: "",
    pageRef: "",
    entityRef: "",
    comments: "",
    reqMethod: "",
    controllerRef: "",
  },

  postTestAPI: {
    name: "",
    url: "",
    authRequired: true,
    title: "",
    description: "",
    keywords: "",
    extraInfo: "",
    source: "",
    _status: "",
    pageRef: "",
    entityRef: "",
    comments: "",
    reqMethod: "",
    controllerRef: "",
  },
};
export { RoutesRegistry };
